# Generated by Django 3.0.1 on 2020-04-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='登录名')),
                ('password', models.CharField(max_length=255, verbose_name='登录密码')),
                ('nickname', models.CharField(max_length=255, verbose_name='用户昵称')),
            ],
            options={
                'verbose_name_plural': '用户个人信息',
                'db_table': 'user',
                'managed': True,
            },
        ),
    ]
