# Generated by Django 3.0.1 on 2020-04-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名字')),
                ('author', models.CharField(max_length=500, verbose_name='作者')),
                ('img', models.CharField(max_length=500, verbose_name='图片')),
                ('price', models.FloatField(verbose_name='价格')),
                ('publish_time', models.CharField(max_length=100, verbose_name='出版日期')),
                ('score', models.FloatField(verbose_name='评分')),
                ('judge', models.IntegerField(verbose_name='评价人数')),
                ('rec_most', models.IntegerField(verbose_name='力荐人数')),
                ('rec_more', models.IntegerField(verbose_name='推荐人数')),
                ('rec_normal', models.IntegerField(verbose_name='还行人数')),
                ('rec_bad', models.IntegerField(verbose_name='较差人数')),
                ('rec_morebad', models.IntegerField(verbose_name='很差人数')),
                ('readed', models.IntegerField(verbose_name='读过')),
                ('reading', models.IntegerField(verbose_name='在读')),
                ('readup', models.IntegerField(verbose_name='想读')),
                ('mess', models.CharField(max_length=1000, verbose_name='图书信息')),
                ('tag', models.CharField(blank=True, max_length=200, null=True, verbose_name='标签')),
            ],
            options={
                'verbose_name_plural': '图书信息',
                'db_table': 'book',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField(unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名字')),
            ],
            options={
                'verbose_name_plural': '标签类别',
                'db_table': 'cate',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名字')),
                ('time', models.DateTimeField(verbose_name='时间')),
                ('action', models.CharField(max_length=64, verbose_name='动作')),
                ('bookname', models.CharField(max_length=64, verbose_name='图书名称')),
                ('bookid', models.IntegerField(verbose_name='图书Id')),
            ],
            options={
                'verbose_name_plural': '行为信息',
                'db_table': 'history',
                'managed': True,
            },
        ),
    ]
