# Generated by Django 3.0.1 on 2020-04-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='img',
            field=models.CharField(default='', max_length=500, verbose_name='图片'),
        ),
    ]
